/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics (unauthenticated) */
        get: {
            parameters: {
                query?: {
                    /** @description Force HTML browse view or Prometheus text. Browsers default to HTML via Accept. */
                    format?: "html" | "prometheus" | "prom" | "text" | "openmetrics";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus text for scrapers. Browsers (Accept text/html) get a grouped HTML view. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/openmetrics-text": string;
                        "text/html": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register user */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Audience BFF. Required on register, login, refresh, logout. Missing → 400. Admin register forbidden. Admin login requires is_system_admin. */
                    "X-Client": components["parameters"]["XClient"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Audience BFF. Required on register, login, refresh, logout. Missing → 400. Admin register forbidden. Admin login requires is_system_admin. */
                    "X-Client": components["parameters"]["XClient"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponseEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh tokens */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Audience BFF. Required on register, login, refresh, logout. Missing → 400. Admin register forbidden. Admin login requires is_system_admin. */
                    "X-Client": components["parameters"]["XClient"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyRequest"];
                };
            };
            responses: {
                /** @description Verified */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordForgotRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm password reset */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordResetRequest"];
                };
            };
            responses: {
                /** @description Reset */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Audience BFF. Required on register, login, refresh, logout. Missing → 400. Admin register forbidden. Admin login requires is_system_admin. */
                    "X-Client": components["parameters"]["XClient"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["MeResponse"];
                        };
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update own profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["MeResponse"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my organizations */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description BCP-47. First supported tag (vi, en) wins. Missing or unknown → vi. */
                    "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Organization"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create organization */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description BCP-47. First supported tag (vi, en) wins. Missing or unknown → vi. */
                    "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrganizationRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Organization"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List staff */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["OrganizationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite staff */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["OrganizationId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InviteRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept invitation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AcceptInviteRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin health (system admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @enum {string} */
            code: "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "VALIDATION" | "BAD_REQUEST" | "TOO_MANY_REQUESTS" | "INTERNAL";
            message: string;
            details?: components["schemas"]["ErrorDetail"][];
        };
        ErrorDetail: {
            field: string;
            /** @enum {string} */
            code: "REQUIRED" | "EMAIL_INVALID" | "TOO_SHORT" | "TOO_LONG" | "UUID_INVALID" | "ONE_OF" | "INVALID" | "PASSWORD_POLICY";
            message: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** @description At least 8 characters; must include uppercase, lowercase, a number, and a special character. */
            password: string;
            full_name?: string;
            first_name?: string;
            last_name?: string;
            phone?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        VerifyRequest: {
            token: string;
        };
        PasswordForgotRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetRequest: {
            token: string;
            /** @description At least 8 characters; must include uppercase, lowercase, a number, and a special character. */
            new_password: string;
        };
        Organization: {
            /** Format: uuid */
            id: string;
            public_id: string;
            /** Format: uuid */
            tenant_id: string;
            code: string;
            /** @description Resolved from Accept-Language */
            name: string;
            name_en?: string;
            name_vi?: string;
            /** Format: email */
            email?: string;
            status: string;
        };
        /** @description At least one of name, name_en, or name_vi is required. */
        CreateOrganizationRequest: {
            /** @description Alias for name_vi when name_vi is omitted */
            name?: string;
            name_en?: string;
            name_vi?: string;
            code?: string;
            /** Format: email */
            email?: string;
        };
        InviteRequest: {
            /** Format: email */
            email: string;
            role_code?: string;
        };
        AcceptInviteRequest: {
            token: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            public_id: string;
            /** Format: email */
            email?: string;
            full_name?: string;
            first_name?: string;
            last_name?: string;
            display_name?: string;
            phone?: string;
            status: string;
            is_system_admin: boolean;
            /**
             * Format: date-time
             * @description UTC
             */
            email_verified_at?: string;
            /**
             * Format: date-time
             * @description UTC
             */
            phone_verified_at?: string;
            /** Format: uuid */
            locale_id?: string;
            timezone?: string;
            /** Format: uuid */
            country_id?: string;
            preferred_currency_code?: string;
            /** @enum {string} */
            theme?: "light" | "dark" | "system";
            /** @enum {string} */
            date_format?: "dmy" | "mdy" | "ymd";
            roles?: string[];
        };
        UpdateProfileRequest: {
            first_name?: string;
            last_name?: string;
            full_name?: string;
            display_name?: string;
            phone?: string;
            /** Format: uuid */
            locale_id?: string;
            timezone?: string;
            /** Format: uuid */
            country_id?: string;
            preferred_currency_code?: string;
            /** @enum {string} */
            theme?: "light" | "dark" | "system";
            /** @enum {string} */
            date_format?: "dmy" | "mdy" | "ymd";
        };
        MeResponse: {
            user?: components["schemas"]["User"];
        };
        TokenResponseEnvelope: {
            data?: {
                access_token?: string;
                refresh_token?: string;
                /** Format: date-time */
                expires_at?: string;
                token_type?: string;
                user?: components["schemas"]["User"];
            };
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Malformed JSON body */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "BAD_REQUEST",
                 *       "message": "invalid json body"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Field validation failed */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "VALIDATION",
                 *       "message": "invalid request",
                 *       "details": [
                 *         {
                 *           "field": "email",
                 *           "code": "REQUIRED",
                 *           "message": "email is required"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        OrganizationId: string;
        /** @description BCP-47. First supported tag (vi, en) wins. Missing or unknown → vi. */
        AcceptLanguage: string;
        /** @description 32-char hex OpenTelemetry trace id (Loki join key). Echoed on the response. Prefer traceparent; if only this header is sent (UUID or hex), Go synthesizes a traceparent. */
        TraceID: string;
        /** @description W3C Trace Context. Propagated BFF → API → Asynq. Echoed on the response when a span is active. */
        Traceparent: string;
        /** @description Audience BFF. Required on register, login, refresh, logout. Missing → 400. Admin register forbidden. Admin login requires is_system_admin. */
        XClient: "player" | "owner" | "admin";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
