/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics (unauthenticated) */
        get: {
            parameters: {
                query?: {
                    /** @description Force HTML browse view or Prometheus text. Browsers default to HTML via Accept. */
                    format?: "html" | "prometheus" | "prom" | "text" | "openmetrics";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus text for scrapers. Browsers (Accept text/html) get a grouped HTML view. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/openmetrics-text": string;
                        "text/html": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register user */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Audience BFF. Required on register, login, refresh, logout. Missing → 400. Admin register forbidden. Admin login requires is_system_admin. */
                    "X-Client": components["parameters"]["XClient"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Audience BFF. Required on register, login, refresh, logout. Missing → 400. Admin register forbidden. Admin login requires is_system_admin. */
                    "X-Client": components["parameters"]["XClient"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponseEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh tokens */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Audience BFF. Required on register, login, refresh, logout. Missing → 400. Admin register forbidden. Admin login requires is_system_admin. */
                    "X-Client": components["parameters"]["XClient"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyRequest"];
                };
            };
            responses: {
                /** @description Verified */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordForgotRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm password reset */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordResetRequest"];
                };
            };
            responses: {
                /** @description Reset */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Audience BFF. Required on register, login, refresh, logout. Missing → 400. Admin register forbidden. Admin login requires is_system_admin. */
                    "X-Client": components["parameters"]["XClient"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["MeResponse"];
                        };
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update own profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["MeResponse"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my organizations */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description BCP-47. First supported tag (vi, en) wins. Missing or unknown → vi. */
                    "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Organization"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create organization
         * @description Creates tenant, organization, default business unit (`code=default`), and owner staff with `org_owner`.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description BCP-47. First supported tag (vi, en) wins. Missing or unknown → vi. */
                    "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrganizationRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Organization"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get organization */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description BCP-47. First supported tag (vi, en) wins. Missing or unknown → vi. */
                    "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                    /** @description If present on nested `/organizations/{id}/...` routes, must match path id. */
                    "X-Organization-ID"?: components["parameters"]["XOrganizationIdOptional"];
                };
                path: {
                    id: components["parameters"]["OrganizationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Organization"];
                        };
                    };
                };
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update organization
         * @description Owner or system admin. Does not change status.
         */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    /** @description BCP-47. First supported tag (vi, en) wins. Missing or unknown → vi. */
                    "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                    /** @description If present on nested `/organizations/{id}/...` routes, must match path id. */
                    "X-Organization-ID"?: components["parameters"]["XOrganizationIdOptional"];
                };
                path: {
                    id: components["parameters"]["OrganizationId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateOrganizationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Organization"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        trace?: never;
    };
    "/api/v1/organizations/{id}/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List staff */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description If present on nested `/organizations/{id}/...` routes, must match path id. */
                    "X-Organization-ID"?: components["parameters"]["XOrganizationIdOptional"];
                };
                path: {
                    id: components["parameters"]["OrganizationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["StaffMember"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Add staff directly
         * @description Owner only. Body uses existing `user_id`. Default role `org_staff`.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description If present on nested `/organizations/{id}/...` routes, must match path id. */
                    "X-Organization-ID"?: components["parameters"]["XOrganizationIdOptional"];
                };
                path: {
                    id: components["parameters"]["OrganizationId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddStaffRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["StaffMember"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                409: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/staff/{staffId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove staff
         * @description Sets status resigned and revokes tenant roles. Cannot remove last owner.
         */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    /** @description If present on nested `/organizations/{id}/...` routes, must match path id. */
                    "X-Organization-ID"?: components["parameters"]["XOrganizationIdOptional"];
                };
                path: {
                    id: components["parameters"]["OrganizationId"];
                    staffId: components["parameters"]["StaffId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        /** Update staff */
        patch: {
            parameters: {
                query?: never;
                header?: {
                    /** @description If present on nested `/organizations/{id}/...` routes, must match path id. */
                    "X-Organization-ID"?: components["parameters"]["XOrganizationIdOptional"];
                };
                path: {
                    id: components["parameters"]["OrganizationId"];
                    staffId: components["parameters"]["StaffId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateStaffRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["StaffMember"];
                        };
                    };
                };
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/api/v1/organizations/{id}/staff/{staffId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend staff */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description If present on nested `/organizations/{id}/...` routes, must match path id. */
                    "X-Organization-ID"?: components["parameters"]["XOrganizationIdOptional"];
                };
                path: {
                    id: components["parameters"]["OrganizationId"];
                    staffId: components["parameters"]["StaffId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Suspended */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/staff/{staffId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore staff */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description If present on nested `/organizations/{id}/...` routes, must match path id. */
                    "X-Organization-ID"?: components["parameters"]["XOrganizationIdOptional"];
                };
                path: {
                    id: components["parameters"]["OrganizationId"];
                    staffId: components["parameters"]["StaffId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Restored */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/staff/{staffId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign seeded role
         * @description Seed roles only (`org_owner`, `org_staff`).
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description If present on nested `/organizations/{id}/...` routes, must match path id. */
                    "X-Organization-ID"?: components["parameters"]["XOrganizationIdOptional"];
                };
                path: {
                    id: components["parameters"]["OrganizationId"];
                    staffId: components["parameters"]["StaffId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignRoleRequest"];
                };
            };
            responses: {
                /** @description Assigned */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/staff/{staffId}/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove role
         * @description Cannot remove last `org_owner`.
         */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    /** @description If present on nested `/organizations/{id}/...` routes, must match path id. */
                    "X-Organization-ID"?: components["parameters"]["XOrganizationIdOptional"];
                };
                path: {
                    id: components["parameters"]["OrganizationId"];
                    staffId: components["parameters"]["StaffId"];
                    roleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite staff
         * @description Owner only. Invitee must not already be an active/suspended member.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description If present on nested `/organizations/{id}/...` routes, must match path id. */
                    "X-Organization-ID"?: components["parameters"]["XOrganizationIdOptional"];
                };
                path: {
                    id: components["parameters"]["OrganizationId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InviteRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Invitation"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/invitations/{invitationId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke invitation */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description If present on nested `/organizations/{id}/...` routes, must match path id. */
                    "X-Organization-ID"?: components["parameters"]["XOrganizationIdOptional"];
                };
                path: {
                    id: components["parameters"]["OrganizationId"];
                    invitationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept invitation
         * @description JWT email must match invitation email.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AcceptInviteRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/invitations/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject invitation
         * @description JWT email must match invitation email. Sets status `rejected` (not revoked).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AcceptInviteRequest"];
                };
            };
            responses: {
                /** @description Rejected */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List branches */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Tenant organization context. Required for `/api/v1/branches*`. */
                    "X-Organization-ID": components["parameters"]["XOrganizationId"];
                    /** @description BCP-47. First supported tag (vi, en) wins. Missing or unknown → vi. */
                    "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Branch"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
            };
        };
        put?: never;
        /**
         * Create branch
         * @description Owner only. Initial status `inactive`. Creates empty location_settings (no scheduling rows).
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Tenant organization context. Required for `/api/v1/branches*`. */
                    "X-Organization-ID": components["parameters"]["XOrganizationId"];
                    /** @description BCP-47. First supported tag (vi, en) wins. Missing or unknown → vi. */
                    "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBranchRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Branch"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                409: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get branch */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Tenant organization context. Required for `/api/v1/branches*`. */
                    "X-Organization-ID": components["parameters"]["XOrganizationId"];
                    /** @description BCP-47. First supported tag (vi, en) wins. Missing or unknown → vi. */
                    "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                };
                path: {
                    id: components["parameters"]["BranchId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Branch"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update branch */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description Tenant organization context. Required for `/api/v1/branches*`. */
                    "X-Organization-ID": components["parameters"]["XOrganizationId"];
                    /** @description BCP-47. First supported tag (vi, en) wins. Missing or unknown → vi. */
                    "Accept-Language"?: components["parameters"]["AcceptLanguage"];
                };
                path: {
                    id: components["parameters"]["BranchId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBranchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Branch"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        trace?: never;
    };
    "/api/v1/branches/{id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open branch
         * @description inactive -> active
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Tenant organization context. Required for `/api/v1/branches*`. */
                    "X-Organization-ID": components["parameters"]["XOrganizationId"];
                };
                path: {
                    id: components["parameters"]["BranchId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Opened */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close branch
         * @description active -> inactive
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Tenant organization context. Required for `/api/v1/branches*`. */
                    "X-Organization-ID": components["parameters"]["XOrganizationId"];
                };
                path: {
                    id: components["parameters"]["BranchId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Closed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive branch
         * @description Any non-archived status -> archived. Booking checks deferred until Booking exists.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Tenant organization context. Required for `/api/v1/branches*`. */
                    "X-Organization-ID": components["parameters"]["XOrganizationId"];
                };
                path: {
                    id: components["parameters"]["BranchId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Archived */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Error"];
                403: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin health (system admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @enum {string} */
            code: "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "VALIDATION" | "BAD_REQUEST" | "TOO_MANY_REQUESTS" | "INTERNAL";
            message: string;
            details?: components["schemas"]["ErrorDetail"][];
        };
        ErrorDetail: {
            field: string;
            /** @enum {string} */
            code: "REQUIRED" | "EMAIL_INVALID" | "TOO_SHORT" | "TOO_LONG" | "UUID_INVALID" | "ONE_OF" | "INVALID" | "PASSWORD_POLICY";
            message: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** @description At least 8 characters; must include uppercase, lowercase, a number, and a special character. */
            password: string;
            full_name?: string;
            first_name?: string;
            last_name?: string;
            phone?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        VerifyRequest: {
            token: string;
        };
        PasswordForgotRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetRequest: {
            token: string;
            /** @description At least 8 characters; must include uppercase, lowercase, a number, and a special character. */
            new_password: string;
        };
        Organization: {
            /** Format: uuid */
            id: string;
            public_id: string;
            /** Format: uuid */
            tenant_id: string;
            code: string;
            /** @description Resolved from Accept-Language */
            name: string;
            name_en?: string;
            name_vi?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            status: string;
        };
        /** @description At least one of name, name_en, or name_vi is required. */
        CreateOrganizationRequest: {
            /** @description Alias for name_vi when name_vi is omitted */
            name?: string;
            name_en?: string;
            name_vi?: string;
            code?: string;
            /** Format: email */
            email?: string;
            phone?: string;
        };
        UpdateOrganizationRequest: {
            name_en?: string;
            name_vi?: string;
            code?: string;
            /** Format: email */
            email?: string;
            phone?: string;
        };
        StaffMember: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            title?: string;
            /** Format: uuid */
            location_id?: string;
            /** @enum {string} */
            status: "invited" | "active" | "suspended" | "resigned";
            roles: string[];
        };
        AddStaffRequest: {
            /** Format: uuid */
            user_id: string;
            title?: string;
            /**
             * @default org_staff
             * @enum {string}
             */
            role_code: "org_owner" | "org_staff";
        };
        UpdateStaffRequest: {
            title?: string;
            /** Format: uuid */
            location_id?: string;
        };
        AssignRoleRequest: {
            /** @enum {string} */
            role_code: "org_owner" | "org_staff";
        };
        InviteRequest: {
            /** Format: email */
            email: string;
            /**
             * @default org_staff
             * @enum {string}
             */
            role_code: "org_owner" | "org_staff";
        };
        Invitation: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role_code: string;
            token: string;
            /** Format: date-time */
            expires_at: string;
        };
        AcceptInviteRequest: {
            token: string;
        };
        BranchAddress: {
            /** Format: uuid */
            country_id?: string;
            state?: string;
            city?: string;
            district?: string;
            ward?: string;
            address_line_1?: string;
            address_line_2?: string;
            postal_code?: string;
        };
        Branch: {
            /** Format: uuid */
            id: string;
            public_id: string;
            /** Format: uuid */
            organization_id: string;
            code: string;
            /** @description Resolved from Accept-Language */
            name: string;
            name_en?: string;
            name_vi?: string;
            phone?: string;
            /** Format: email */
            email?: string;
            timezone?: string;
            /** @enum {string} */
            status: "active" | "inactive" | "maintenance" | "archived";
            address?: components["schemas"]["BranchAddress"];
        };
        /** @description At least one of name_en or name_vi is required. Initial status is inactive. */
        CreateBranchRequest: {
            name_en?: string;
            name_vi?: string;
            code?: string;
            phone?: string;
            /** Format: email */
            email?: string;
            timezone?: string;
            address?: components["schemas"]["BranchAddress"];
        };
        UpdateBranchRequest: {
            name_en?: string;
            name_vi?: string;
            code?: string;
            phone?: string;
            /** Format: email */
            email?: string;
            timezone?: string;
            address?: components["schemas"]["BranchAddress"];
        };
        User: {
            /** Format: uuid */
            id: string;
            public_id: string;
            /** Format: email */
            email?: string;
            full_name?: string;
            first_name?: string;
            last_name?: string;
            display_name?: string;
            phone?: string;
            status: string;
            is_system_admin: boolean;
            /**
             * Format: date-time
             * @description UTC
             */
            email_verified_at?: string;
            /**
             * Format: date-time
             * @description UTC
             */
            phone_verified_at?: string;
            /** Format: uuid */
            locale_id?: string;
            timezone?: string;
            /** Format: uuid */
            country_id?: string;
            preferred_currency_code?: string;
            /** @enum {string} */
            theme?: "light" | "dark" | "system";
            /** @enum {string} */
            date_format?: "dmy" | "mdy" | "ymd";
            roles?: string[];
        };
        UpdateProfileRequest: {
            first_name?: string;
            last_name?: string;
            full_name?: string;
            display_name?: string;
            phone?: string;
            /** Format: uuid */
            locale_id?: string;
            timezone?: string;
            /** Format: uuid */
            country_id?: string;
            preferred_currency_code?: string;
            /** @enum {string} */
            theme?: "light" | "dark" | "system";
            /** @enum {string} */
            date_format?: "dmy" | "mdy" | "ymd";
        };
        MeResponse: {
            user?: components["schemas"]["User"];
        };
        TokenResponseEnvelope: {
            data?: {
                access_token?: string;
                refresh_token?: string;
                /** Format: date-time */
                expires_at?: string;
                token_type?: string;
                user?: components["schemas"]["User"];
            };
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Malformed JSON body */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "BAD_REQUEST",
                 *       "message": "invalid json body"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Field validation failed */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "VALIDATION",
                 *       "message": "invalid request",
                 *       "details": [
                 *         {
                 *           "field": "email",
                 *           "code": "REQUIRED",
                 *           "message": "email is required"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        OrganizationId: string;
        StaffId: string;
        BranchId: string;
        /** @description Tenant organization context. Required for `/api/v1/branches*`. */
        XOrganizationId: string;
        /** @description If present on nested `/organizations/{id}/...` routes, must match path id. */
        XOrganizationIdOptional: string;
        /** @description BCP-47. First supported tag (vi, en) wins. Missing or unknown → vi. */
        AcceptLanguage: string;
        /** @description 32-char hex OpenTelemetry trace id (Loki join key). Echoed on the response. Prefer traceparent; if only this header is sent (UUID or hex), Go synthesizes a traceparent. */
        TraceID: string;
        /** @description W3C Trace Context. Propagated BFF → API → Asynq. Echoed on the response when a span is active. */
        Traceparent: string;
        /** @description Audience BFF. Required on register, login, refresh, logout. Missing → 400. Admin register forbidden. Admin login requires is_system_admin. */
        XClient: "player" | "owner" | "admin";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
