/** @todo Replace with API-backed data when admin org analytics endpoints exist. */

export const DETAIL_MOCK = {
  province: "TP. HCM",
  sport: "Badminton",
  owner: "Nguyen Van Hung",
  verified: true,
  plan: "enterprise" as const,
  courts: 42,
  staff: 38,
  players: 2840,
  monthlyGmv: "284M",
  occupancy: 87,
  healthScore: 94,
  revenueTrend: [180, 210, 195, 240, 258, 284] as const,
  revenueMonths: ["Mar", "Apr", "May", "Jun", "Jul", "Aug"] as const,
  topBranches: [
    { name: "District 7", courts: 8, occupancy: 92, revenue: "78M" },
    { name: "Binh Thanh", courts: 7, occupancy: 85, revenue: "64M" },
    { name: "District 1", courts: 6, occupancy: 76, revenue: "52M" },
  ] as const,
  healthBreakdown: [
    { labelKey: "operations" as const, score: 96 },
    { labelKey: "finance" as const, score: 92 },
    { labelKey: "satisfaction" as const, score: 88 },
    { labelKey: "compliance" as const, score: 95 },
    { labelKey: "growth" as const, score: 78 },
  ] as const,
  aiInsights: ["insight1", "insight2", "insight3"] as const,
  tasks: [
    { labelKey: "task1" as const, priority: "high" as const, due: "25/08" },
    { labelKey: "task2" as const, priority: "medium" as const, due: "30/08" },
    { labelKey: "task3" as const, priority: "low" as const, due: "05/09" },
  ] as const,
  riskAlert: "riskAlert" as const,
  branches: [
    { name: "District 7", manager: "Tran Minh Quan", courts: 8, occupancy: 92, revenue: "78M", status: "active" as const },
    { name: "Binh Thanh", manager: "Le Huong Giang", courts: 7, occupancy: 85, revenue: "64M", status: "active" as const },
    { name: "District 1", manager: "Nguyen Thu Ha", courts: 6, occupancy: 76, revenue: "52M", status: "active" as const },
    { name: "Binh Duong", manager: "Pham Anh Khoa", courts: 9, occupancy: 68, revenue: "58M", status: "active" as const },
    { name: "Thu Duc", manager: "Vu Quoc Hung", courts: 6, occupancy: 55, revenue: "38M", status: "active" as const },
    { name: "Go Vap", manager: "Do Thanh Lan", courts: 6, occupancy: 44, revenue: "24M", status: "maintenance" as const },
  ] as const,
  mapPins: [
    { name: "D7", x: 42, y: 68, occupancy: 92 },
    { name: "BT", x: 52, y: 44, occupancy: 85 },
    { name: "D1", x: 47, y: 55, occupancy: 76 },
    { name: "BD", x: 72, y: 30, occupancy: 68 },
    { name: "TD", x: 63, y: 40, occupancy: 55 },
    { name: "GV", x: 44, y: 36, occupancy: 44 },
  ] as const,
  courtPortfolio: [
    { name: "Court A1", sport: "Badminton", surface: "Wood", indoor: true, occupancy: 94, maintenance: "ok" as const, bookingRate: "98%", branch: "D7" },
    { name: "Court A2", sport: "Badminton", surface: "Wood", indoor: true, occupancy: 88, maintenance: "ok" as const, bookingRate: "92%", branch: "D7" },
    { name: "Court B1", sport: "Pickleball", surface: "Rubber", indoor: false, occupancy: 72, maintenance: "ok" as const, bookingRate: "78%", branch: "Binh Thanh" },
    { name: "Court B2", sport: "Pickleball", surface: "Rubber", indoor: false, occupancy: 65, maintenance: "scheduled" as const, bookingRate: "70%", branch: "Binh Thanh" },
    { name: "Court C1", sport: "Badminton", surface: "PVC", indoor: true, occupancy: 81, maintenance: "ok" as const, bookingRate: "85%", branch: "D1" },
    { name: "Court C2", sport: "Badminton", surface: "PVC", indoor: true, occupancy: 55, maintenance: "urgent" as const, bookingRate: "58%", branch: "D1" },
  ] as const,
  team: [
    { name: "Nguyen Van Hung", roleKey: "owner" as const, branch: "All", lastLogin: "22/08/2026", status: "active" as const, initials: "NH" },
    { name: "Tran Minh Quan", roleKey: "branchManager" as const, branch: "D7", lastLogin: "22/08/2026", status: "active" as const, initials: "TQ" },
    { name: "Le Huong Giang", roleKey: "branchManager" as const, branch: "Binh Thanh", lastLogin: "21/08/2026", status: "active" as const, initials: "LG" },
    { name: "Pham Anh Khoa", roleKey: "receptionist" as const, branch: "D7", lastLogin: "22/08/2026", status: "active" as const, initials: "PK" },
    { name: "Vu Quoc Hung", roleKey: "cashier" as const, branch: "Binh Thanh", lastLogin: "20/08/2026", status: "active" as const, initials: "VH" },
    { name: "Do Thanh Lan", roleKey: "coach" as const, branch: "D1", lastLogin: "19/08/2026", status: "inactive" as const, initials: "DL" },
    { name: "Bui Thanh Dat", roleKey: "staff" as const, branch: "Go Vap", lastLogin: "—", status: "pending" as const, initials: "BD" },
  ] as const,
  roleDistribution: [
    { roleKey: "branchManager" as const, count: 2 },
    { roleKey: "receptionist" as const, count: 2 },
    { roleKey: "cashier" as const, count: 1 },
    { roleKey: "coach" as const, count: 1 },
    { roleKey: "staff" as const, count: 2 },
  ] as const,
  billingHistory: [
    { type: "payment" as const, labelKey: "paymentAug" as const, amount: "4,200,000", date: "01/08/2026", status: "paid" as const },
    { type: "payment" as const, labelKey: "paymentJul" as const, amount: "4,200,000", date: "01/07/2026", status: "paid" as const },
    { type: "upgrade" as const, labelKey: "upgradeEnterprise" as const, amount: "+2,000,000", date: "15/06/2026", status: "paid" as const },
  ] as const,
  billingUsage: [
    { labelKey: "branchesUsed" as const, used: 6, total: 10 },
    { labelKey: "courtsUsed" as const, used: 42, total: 60 },
    { labelKey: "staffSeats" as const, used: 38, total: 50 },
    { labelKey: "apiCalls" as const, used: 8200, total: 50000 },
  ] as const,
  activityEvents: [
    { cat: "operation" as const, labelKey: "event1" as const, detailKey: "event1Detail" as const, time: "15/08/2026" },
    { cat: "revenue" as const, labelKey: "event2" as const, detailKey: "event2Detail" as const, time: "10/08/2026" },
    { cat: "staff" as const, labelKey: "event3" as const, detailKey: "event3Detail" as const, time: "05/08/2026" },
    { cat: "verification" as const, labelKey: "event4" as const, detailKey: "event4Detail" as const, time: "02/03/2026" },
  ] as const,
} as const;
