-- Generated by scripts/sqlc-schema.sh — do not edit by hand.
-- Source: backend/migrations (-- +goose Up only).

-- >>> 00001_infrastructure.sql
CREATE SCHEMA IF NOT EXISTS infrastructure;

CREATE TYPE infrastructure.event_status AS ENUM ('pending', 'published', 'failed', 'ignored');

CREATE TABLE infrastructure.idempotency_keys (
    id              uuid PRIMARY KEY,
    scope           varchar(100) NOT NULL,
    key_hash        varchar(255) NOT NULL,
    request_hash    varchar(255),
    response_status int,
    response_body   jsonb,
    expires_at      timestamptz NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (scope, key_hash)
);

CREATE TABLE infrastructure.domain_events (
    id              uuid PRIMARY KEY,
    event_type      varchar(150) NOT NULL,
    aggregate_type  varchar(100) NOT NULL,
    aggregate_id    uuid NOT NULL,
    payload         jsonb NOT NULL DEFAULT '{}'::jsonb,
    metadata        jsonb NOT NULL DEFAULT '{}'::jsonb,
    status          infrastructure.event_status NOT NULL DEFAULT 'pending',
    occurred_at     timestamptz NOT NULL DEFAULT now(),
    published_at    timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX domain_events_status_idx ON infrastructure.domain_events (status);
CREATE INDEX domain_events_aggregate_idx ON infrastructure.domain_events (aggregate_type, aggregate_id);

CREATE TABLE infrastructure.outbox_events (
    id              uuid PRIMARY KEY,
    event_id        uuid NOT NULL REFERENCES infrastructure.domain_events (id),
    destination     varchar(150) NOT NULL,
    payload         jsonb NOT NULL DEFAULT '{}'::jsonb,
    status          infrastructure.event_status NOT NULL DEFAULT 'pending',
    attempts        int NOT NULL DEFAULT 0,
    available_at    timestamptz NOT NULL DEFAULT now(),
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX outbox_events_status_available_idx ON infrastructure.outbox_events (status, available_at);


-- >>> 00002_identity.sql
CREATE SCHEMA IF NOT EXISTS identity;

CREATE TYPE identity.user_status AS ENUM ('pending', 'active', 'suspended', 'locked', 'deleted');
CREATE TYPE identity.gender AS ENUM ('male', 'female', 'other', 'undisclosed');
CREATE TYPE identity.identity_provider AS ENUM ('local', 'google', 'apple', 'facebook', 'github', 'microsoft', 'oidc', 'saml');
CREATE TYPE identity.verification_status AS ENUM ('pending', 'verified', 'rejected');
CREATE TYPE identity.role_scope AS ENUM ('system', 'tenant');
CREATE TYPE identity.session_status AS ENUM ('active', 'expired', 'revoked');
CREATE TYPE identity.mfa_type AS ENUM ('totp', 'sms', 'email');

CREATE TABLE identity.users (
    id               uuid PRIMARY KEY,
    public_id        varchar(26) NOT NULL,
    status           identity.user_status NOT NULL,
    is_system_admin  boolean NOT NULL DEFAULT false,
    last_login_at    timestamptz,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    deleted_at       timestamptz
);

CREATE UNIQUE INDEX users_public_id_uidx ON identity.users (public_id);
CREATE INDEX users_status_idx ON identity.users (status);

CREATE TABLE identity.user_profiles (
    id            uuid PRIMARY KEY,
    user_id       uuid NOT NULL UNIQUE REFERENCES identity.users (id),
    first_name    varchar(100),
    last_name     varchar(100),
    full_name     varchar(255) NOT NULL,
    display_name  varchar(255),
    avatar_file_id uuid,
    gender        identity.gender,
    date_of_birth date,
    timezone      varchar(100),
    locale_id     uuid,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE identity.identities (
    id               uuid PRIMARY KEY,
    user_id          uuid NOT NULL REFERENCES identity.users (id),
    provider         identity.identity_provider NOT NULL,
    provider_subject varchar(255) NOT NULL,
    email            varchar(255),
    phone            varchar(30),
    is_primary       boolean NOT NULL DEFAULT false,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX identities_user_id_idx ON identity.identities (user_id);
CREATE UNIQUE INDEX identities_provider_subject_uidx ON identity.identities (provider, provider_subject);
CREATE UNIQUE INDEX identities_local_email_uidx ON identity.identities (email) WHERE provider = 'local' AND email IS NOT NULL;

CREATE TABLE identity.identity_verifications (
    id           uuid PRIMARY KEY,
    identity_id  uuid NOT NULL REFERENCES identity.identities (id),
    status       identity.verification_status NOT NULL,
    token_hash   varchar(255) NOT NULL,
    verified_at  timestamptz,
    expires_at   timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX identity_verifications_identity_id_idx ON identity.identity_verifications (identity_id);

CREATE TABLE identity.roles (
    id             uuid PRIMARY KEY,
    code           varchar(100) NOT NULL,
    name_en        varchar(255) NOT NULL,
    name_vi        varchar(255) NOT NULL,
    scope          identity.role_scope NOT NULL,
    description_en text,
    description_vi text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX roles_code_uidx ON identity.roles (code);

CREATE TABLE identity.permissions (
    id             uuid PRIMARY KEY,
    code           varchar(150) NOT NULL,
    name_en        varchar(255) NOT NULL,
    name_vi        varchar(255) NOT NULL,
    description_en text,
    description_vi text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX permissions_code_uidx ON identity.permissions (code);

CREATE TABLE identity.role_permissions (
    role_id       uuid NOT NULL REFERENCES identity.roles (id),
    permission_id uuid NOT NULL REFERENCES identity.permissions (id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE identity.user_roles (
    id          uuid PRIMARY KEY,
    tenant_id   uuid,
    user_id     uuid NOT NULL REFERENCES identity.users (id),
    role_id     uuid NOT NULL REFERENCES identity.roles (id),
    assigned_by uuid,
    assigned_at timestamptz NOT NULL DEFAULT now(),
    expires_at  timestamptz
);

CREATE UNIQUE INDEX user_roles_unique_uidx ON identity.user_roles (tenant_id, user_id, role_id) NULLS NOT DISTINCT;
CREATE INDEX user_roles_user_id_idx ON identity.user_roles (user_id);

CREATE TABLE identity.password_credentials (
    id                   uuid PRIMARY KEY,
    user_id              uuid NOT NULL UNIQUE REFERENCES identity.users (id),
    password_hash        text NOT NULL,
    password_changed_at  timestamptz,
    password_expires_at  timestamptz,
    failed_attempts      int NOT NULL DEFAULT 0,
    locked_until         timestamptz,
    updated_at           timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE identity.password_reset_tokens (
    id          uuid PRIMARY KEY,
    user_id     uuid NOT NULL REFERENCES identity.users (id),
    token_hash  varchar(255) NOT NULL,
    expires_at  timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX password_reset_tokens_user_id_idx ON identity.password_reset_tokens (user_id);

CREATE TABLE identity.sessions (
    id               uuid PRIMARY KEY,
    user_id          uuid NOT NULL REFERENCES identity.users (id),
    device_id        uuid,
    status           identity.session_status NOT NULL,
    ip_address       inet,
    user_agent       text,
    last_activity_at timestamptz,
    expires_at       timestamptz NOT NULL,
    created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX sessions_user_id_idx ON identity.sessions (user_id);
CREATE INDEX sessions_status_idx ON identity.sessions (status);

CREATE TABLE identity.refresh_tokens (
    id          uuid PRIMARY KEY,
    session_id  uuid NOT NULL REFERENCES identity.sessions (id),
    token_hash  varchar(255) NOT NULL,
    expires_at  timestamptz NOT NULL,
    revoked_at  timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX refresh_tokens_session_id_idx ON identity.refresh_tokens (session_id);
CREATE UNIQUE INDEX refresh_tokens_token_hash_uidx ON identity.refresh_tokens (token_hash);

CREATE TABLE identity.login_histories (
    id          uuid PRIMARY KEY,
    user_id     uuid NOT NULL REFERENCES identity.users (id),
    session_id  uuid REFERENCES identity.sessions (id),
    is_success  boolean NOT NULL,
    ip_address  inet,
    user_agent  text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX login_histories_user_id_idx ON identity.login_histories (user_id);

CREATE TABLE identity.mfa_methods (
    id          uuid PRIMARY KEY,
    user_id     uuid NOT NULL REFERENCES identity.users (id),
    type        identity.mfa_type NOT NULL,
    secret_enc  text,
    is_enabled  boolean NOT NULL DEFAULT false,
    verified_at timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX mfa_methods_user_id_idx ON identity.mfa_methods (user_id);

CREATE TABLE identity.mfa_recovery_codes (
    id          uuid PRIMARY KEY,
    user_id     uuid NOT NULL REFERENCES identity.users (id),
    code_hash   varchar(255) NOT NULL,
    consumed_at timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX mfa_recovery_codes_user_id_idx ON identity.mfa_recovery_codes (user_id);


-- >>> 00003_organization.sql
CREATE SCHEMA IF NOT EXISTS organization;

CREATE TYPE organization.tenant_status AS ENUM ('trial', 'active', 'suspended', 'canceled');
CREATE TYPE organization.organization_status AS ENUM ('active', 'inactive', 'suspended', 'archived');
CREATE TYPE organization.organization_type AS ENUM ('company', 'club', 'school', 'government', 'individual', 'other');
CREATE TYPE organization.staff_status AS ENUM ('invited', 'active', 'suspended', 'resigned');
CREATE TYPE organization.invitation_status AS ENUM ('pending', 'accepted', 'expired', 'revoked', 'rejected');

CREATE TABLE organization.tenants (
    id         uuid PRIMARY KEY,
    public_id  varchar(26) NOT NULL UNIQUE,
    code       varchar(100) NOT NULL,
    name_en    varchar(255),
    name_vi    varchar(255),
    slug       varchar(150) NOT NULL,
    status     organization.tenant_status NOT NULL,
    timezone   varchar(100),
    locale_id  uuid,
    currency   varchar(10),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT tenants_display_name_chk CHECK (name_en IS NOT NULL OR name_vi IS NOT NULL)
);

CREATE UNIQUE INDEX tenants_code_uidx ON organization.tenants (code);
CREATE UNIQUE INDEX tenants_slug_uidx ON organization.tenants (slug);

CREATE TABLE organization.organizations (
    id                uuid PRIMARY KEY,
    public_id         varchar(26) NOT NULL UNIQUE,
    tenant_id         uuid NOT NULL REFERENCES organization.tenants (id),
    code              varchar(100) NOT NULL,
    name_en           varchar(255),
    name_vi           varchar(255),
    legal_name        varchar(255),
    organization_type organization.organization_type NOT NULL,
    tax_code          varchar(100),
    phone             varchar(30),
    email             varchar(255),
    website           varchar(255),
    logo_file_id      uuid,
    status            organization.organization_status NOT NULL,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    deleted_at        timestamptz,
    CONSTRAINT organizations_display_name_chk CHECK (name_en IS NOT NULL OR name_vi IS NOT NULL)
);

CREATE UNIQUE INDEX organizations_tenant_code_uidx ON organization.organizations (tenant_id, code) WHERE deleted_at IS NULL;
CREATE INDEX organizations_tenant_id_idx ON organization.organizations (tenant_id);
CREATE INDEX organizations_status_idx ON organization.organizations (status);

CREATE TABLE organization.organization_settings (
    id                  uuid PRIMARY KEY,
    organization_id     uuid NOT NULL UNIQUE REFERENCES organization.organizations (id),
    booking_policy      jsonb,
    cancellation_policy jsonb,
    operating_policy    jsonb,
    branding            jsonb,
    updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE organization.staff_members (
    id              uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organization.organizations (id),
    location_id     uuid,
    user_id         uuid NOT NULL,
    employee_code   varchar(100),
    title           varchar(255),
    status          organization.staff_status NOT NULL,
    joined_at       date,
    left_at         date,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX staff_members_organization_id_idx ON organization.staff_members (organization_id);
CREATE INDEX staff_members_user_id_idx ON organization.staff_members (user_id);
CREATE UNIQUE INDEX staff_members_org_employee_uidx ON organization.staff_members (organization_id, employee_code) WHERE employee_code IS NOT NULL;
CREATE UNIQUE INDEX staff_members_org_user_uidx ON organization.staff_members (organization_id, user_id);

CREATE TABLE organization.staff_invitations (
    id               uuid PRIMARY KEY,
    organization_id  uuid NOT NULL REFERENCES organization.organizations (id),
    email            varchar(255) NOT NULL,
    role_code        varchar(100) NOT NULL,
    invitation_token varchar(255) NOT NULL,
    status           organization.invitation_status NOT NULL,
    expires_at       timestamptz NOT NULL,
    invited_by       uuid NOT NULL,
    accepted_by      uuid,
    created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX staff_invitations_organization_id_idx ON organization.staff_invitations (organization_id);
CREATE INDEX staff_invitations_email_idx ON organization.staff_invitations (email);
CREATE UNIQUE INDEX staff_invitations_token_uidx ON organization.staff_invitations (invitation_token);


-- >>> 00004_reference.sql
CREATE SCHEMA IF NOT EXISTS reference;

CREATE TABLE reference.locales (
    id         uuid PRIMARY KEY,
    code       varchar(16) NOT NULL,
    name_en    varchar(255) NOT NULL,
    name_vi    varchar(255) NOT NULL,
    is_default boolean NOT NULL DEFAULT false,
    is_active  boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX locales_code_uidx ON reference.locales (code);
CREATE INDEX locales_is_active_idx ON reference.locales (is_active);
CREATE INDEX locales_is_default_idx ON reference.locales (is_default);

CREATE TABLE reference.countries (
    id         uuid PRIMARY KEY,
    iso2       varchar(2) NOT NULL,
    iso3       varchar(3),
    name_en    varchar(255) NOT NULL,
    name_vi    varchar(255) NOT NULL,
    phone_code varchar(10),
    is_active  boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX countries_iso2_uidx ON reference.countries (iso2);
CREATE UNIQUE INDEX countries_iso3_uidx ON reference.countries (iso3) WHERE iso3 IS NOT NULL;
CREATE INDEX countries_is_active_idx ON reference.countries (is_active);

CREATE TABLE reference.country_translations (
    id         uuid PRIMARY KEY,
    country_id uuid NOT NULL REFERENCES reference.countries (id),
    locale_id  uuid NOT NULL REFERENCES reference.locales (id),
    name       varchar(255) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX country_translations_country_locale_uidx ON reference.country_translations (country_id, locale_id);

CREATE TABLE reference.currencies (
    code           varchar(3) PRIMARY KEY,
    name_en        varchar(255) NOT NULL,
    name_vi        varchar(255) NOT NULL,
    symbol         varchar(10) NOT NULL,
    decimal_places smallint NOT NULL DEFAULT 2,
    is_default     boolean NOT NULL DEFAULT false,
    is_active      boolean NOT NULL DEFAULT true,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX currencies_is_active_idx ON reference.currencies (is_active);

INSERT INTO reference.locales (id, code, name_en, name_vi, is_default, is_active)
VALUES
    ('01900000-0000-7000-8000-000000000010', 'vi', 'Vietnamese', 'Tiếng Việt', true, true),
    ('01900000-0000-7000-8000-000000000011', 'en', 'English', 'Tiếng Anh', false, true);

INSERT INTO reference.countries (id, iso2, iso3, name_en, name_vi, phone_code, is_active)
VALUES
    ('01900000-0000-7000-8000-000000000001', 'VN', 'VNM', 'Vietnam', 'Việt Nam', '+84', true),
    ('01900000-0000-7000-8000-000000000002', 'US', 'USA', 'United States', 'Hoa Kỳ', '+1', true);

INSERT INTO reference.currencies (code, name_en, name_vi, symbol, decimal_places, is_default, is_active)
VALUES
    ('VND', 'Vietnamese Dong', 'Đồng Việt Nam', '₫', 0, true, true),
    ('USD', 'US Dollar', 'Đô la Mỹ', '$', 2, false, true);


-- >>> 00005_platform.sql
CREATE SCHEMA IF NOT EXISTS platform;

CREATE TYPE platform.audit_actor_type AS ENUM ('user', 'staff', 'system', 'integration');
CREATE TYPE platform.audit_log_activity_type AS ENUM (
    'created',
    'updated',
    'deleted',
    'restored',
    'viewed',
    'exported',
    'imported',
    'status_change',
    'assign',
    'login',
    'logout',
    'other'
);

CREATE TABLE platform.audit_logs (
    id              uuid PRIMARY KEY,
    domain_event_id uuid NOT NULL UNIQUE REFERENCES infrastructure.domain_events (id),
    tenant_id       uuid,
    actor_type      platform.audit_actor_type,
    actor_id        uuid,
    entity_type     varchar(100) NOT NULL,
    entity_id       uuid NOT NULL,
    action          platform.audit_log_activity_type NOT NULL,
    before_data     jsonb,
    after_data      jsonb,
    ip_address      inet,
    user_agent      text,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX audit_logs_tenant_id_idx ON platform.audit_logs (tenant_id);
CREATE INDEX audit_logs_entity_idx ON platform.audit_logs (entity_type, entity_id);
CREATE INDEX audit_logs_action_idx ON platform.audit_logs (action);
CREATE INDEX audit_logs_created_at_idx ON platform.audit_logs (created_at);


-- >>> 00006_i18n_locale_fk.sql
-- Reshape identity/organization display names + locale_id when 00002/00003
-- already ran with the pre-i18n columns, then attach FKs to reference.locales.

-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'identity' AND table_name = 'user_profiles' AND column_name = 'locale'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'identity' AND table_name = 'user_profiles' AND column_name = 'locale_id'
    ) THEN
        ALTER TABLE identity.user_profiles ADD COLUMN locale_id uuid;
        UPDATE identity.user_profiles
        SET locale_id = CASE
            WHEN lower(locale) LIKE 'en%' THEN '01900000-0000-7000-8000-000000000011'::uuid
            WHEN locale IS NOT NULL AND btrim(locale) <> '' THEN '01900000-0000-7000-8000-000000000010'::uuid
            ELSE NULL
        END;
        ALTER TABLE identity.user_profiles DROP COLUMN locale;
    END IF;
END $$;
-- +goose StatementEnd

-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'identity' AND table_name = 'roles' AND column_name = 'name'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'identity' AND table_name = 'roles' AND column_name = 'name_en'
    ) THEN
        ALTER TABLE identity.roles
            ADD COLUMN name_en varchar(255),
            ADD COLUMN name_vi varchar(255),
            ADD COLUMN description_en text,
            ADD COLUMN description_vi text;
        UPDATE identity.roles
        SET name_en = name, name_vi = name, description_en = description, description_vi = description;
        ALTER TABLE identity.roles
            ALTER COLUMN name_en SET NOT NULL,
            ALTER COLUMN name_vi SET NOT NULL;
        ALTER TABLE identity.roles DROP COLUMN name, DROP COLUMN description;
    END IF;
END $$;
-- +goose StatementEnd

-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'identity' AND table_name = 'permissions' AND column_name = 'name'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'identity' AND table_name = 'permissions' AND column_name = 'name_en'
    ) THEN
        ALTER TABLE identity.permissions
            ADD COLUMN name_en varchar(255),
            ADD COLUMN name_vi varchar(255),
            ADD COLUMN description_en text,
            ADD COLUMN description_vi text;
        UPDATE identity.permissions
        SET name_en = name, name_vi = name, description_en = description, description_vi = description;
        ALTER TABLE identity.permissions
            ALTER COLUMN name_en SET NOT NULL,
            ALTER COLUMN name_vi SET NOT NULL;
        ALTER TABLE identity.permissions DROP COLUMN name, DROP COLUMN description;
    END IF;
END $$;
-- +goose StatementEnd

-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'organization' AND table_name = 'tenants' AND column_name = 'name'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'organization' AND table_name = 'tenants' AND column_name = 'name_en'
    ) THEN
        ALTER TABLE organization.tenants
            ADD COLUMN name_en varchar(255),
            ADD COLUMN name_vi varchar(255),
            ADD COLUMN locale_id uuid;
        UPDATE organization.tenants
        SET name_vi = name,
            name_en = name,
            locale_id = CASE
                WHEN lower(locale) LIKE 'en%' THEN '01900000-0000-7000-8000-000000000011'::uuid
                ELSE '01900000-0000-7000-8000-000000000010'::uuid
            END;
        ALTER TABLE organization.tenants DROP COLUMN name, DROP COLUMN locale;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenants_display_name_chk') THEN
        ALTER TABLE organization.tenants
            ADD CONSTRAINT tenants_display_name_chk CHECK (name_en IS NOT NULL OR name_vi IS NOT NULL);
    END IF;
END $$;
-- +goose StatementEnd

-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'organization' AND table_name = 'organizations' AND column_name = 'name'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'organization' AND table_name = 'organizations' AND column_name = 'name_en'
    ) THEN
        ALTER TABLE organization.organizations
            ADD COLUMN name_en varchar(255),
            ADD COLUMN name_vi varchar(255);
        UPDATE organization.organizations SET name_vi = name, name_en = name;
        ALTER TABLE organization.organizations DROP COLUMN name;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'organizations_display_name_chk') THEN
        ALTER TABLE organization.organizations
            ADD CONSTRAINT organizations_display_name_chk CHECK (name_en IS NOT NULL OR name_vi IS NOT NULL);
    END IF;
END $$;
-- +goose StatementEnd

-- +goose StatementBegin
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'user_profiles_locale_id_fkey') THEN
        ALTER TABLE identity.user_profiles
            ADD CONSTRAINT user_profiles_locale_id_fkey
            FOREIGN KEY (locale_id) REFERENCES reference.locales (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tenants_locale_id_fkey') THEN
        ALTER TABLE organization.tenants
            ADD CONSTRAINT tenants_locale_id_fkey
            FOREIGN KEY (locale_id) REFERENCES reference.locales (id);
    END IF;
END $$;
-- +goose StatementEnd


-- >>> 00007_user_prefs_and_locales.sql
ALTER TABLE reference.locales ADD COLUMN name varchar(255);
ALTER TABLE reference.locales ADD COLUMN native_name varchar(255);
UPDATE reference.locales SET name = name_en, native_name = name_vi;
ALTER TABLE reference.locales ALTER COLUMN name SET NOT NULL;
ALTER TABLE reference.locales ALTER COLUMN native_name SET NOT NULL;
ALTER TABLE reference.locales DROP COLUMN name_en;
ALTER TABLE reference.locales DROP COLUMN name_vi;

ALTER TABLE identity.users
    ADD COLUMN email_verified_at timestamptz,
    ADD COLUMN phone_verified_at timestamptz;

CREATE TYPE identity.theme AS ENUM ('light', 'dark', 'system');
CREATE TYPE identity.date_format AS ENUM ('dmy', 'mdy', 'ymd');

ALTER TABLE identity.user_profiles
    ADD COLUMN country_id uuid REFERENCES reference.countries (id),
    ADD COLUMN preferred_currency_code varchar(3) REFERENCES reference.currencies (code),
    ADD COLUMN theme identity.theme NOT NULL DEFAULT 'system',
    ADD COLUMN date_format identity.date_format NOT NULL DEFAULT 'dmy';

UPDATE identity.user_profiles
SET country_id = COALESCE(country_id, '01900000-0000-7000-8000-000000000001'),
    preferred_currency_code = COALESCE(preferred_currency_code, 'VND'),
    timezone = COALESCE(NULLIF(timezone, ''), 'Asia/Ho_Chi_Minh');

CREATE UNIQUE INDEX identities_phone_uidx
    ON identity.identities (phone)
    WHERE phone IS NOT NULL AND phone <> '';


-- >>> 00008_login_histories_is_success.sql
-- 00002 on already-applied DBs still has `success`; ERD + current 00002 use `is_success`.
-- +goose StatementBegin
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'identity' AND table_name = 'login_histories' AND column_name = 'success'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'identity' AND table_name = 'login_histories' AND column_name = 'is_success'
    ) THEN
        ALTER TABLE identity.login_histories RENAME COLUMN success TO is_success;
    END IF;
END $$;
-- +goose StatementEnd


-- >>> 00009_user_profiles_id.sql
-- Applied 00002 used user_id as PK; ERD + current 00002 use a separate uuid id.
-- +goose StatementBegin
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'identity' AND table_name = 'user_profiles' AND column_name = 'id'
    ) THEN
        ALTER TABLE identity.user_profiles ADD COLUMN id uuid;
        UPDATE identity.user_profiles SET id = user_id WHERE id IS NULL;
        ALTER TABLE identity.user_profiles ALTER COLUMN id SET NOT NULL;

        ALTER TABLE identity.user_profiles DROP CONSTRAINT user_profiles_pkey;
        ALTER TABLE identity.user_profiles ADD PRIMARY KEY (id);

        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname = 'user_profiles_user_id_key'
        ) THEN
            ALTER TABLE identity.user_profiles ADD CONSTRAINT user_profiles_user_id_key UNIQUE (user_id);
        END IF;
    END IF;
END $$;
-- +goose StatementEnd


-- >>> 00010_organization_w2_branch_staff.sql
-- W2: business units, branches (locations), invitation rejected, default BU backfill.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TYPE organization.invitation_status ADD VALUE IF NOT EXISTS 'rejected';

CREATE TYPE organization.business_unit_status AS ENUM ('active', 'inactive');
CREATE TYPE organization.location_status AS ENUM ('active', 'inactive', 'maintenance', 'archived');

CREATE TABLE organization.business_units (
    id              uuid PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES organization.organizations (id),
    code            varchar(100) NOT NULL,
    name_en         varchar(255),
    name_vi         varchar(255),
    status          organization.business_unit_status NOT NULL DEFAULT 'active',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT business_units_display_name_chk CHECK (name_en IS NOT NULL OR name_vi IS NOT NULL)
);

CREATE UNIQUE INDEX business_units_org_code_uidx ON organization.business_units (organization_id, code);
CREATE INDEX business_units_organization_id_idx ON organization.business_units (organization_id);

CREATE TABLE organization.locations (
    id               uuid PRIMARY KEY,
    public_id        varchar(26) NOT NULL UNIQUE,
    business_unit_id uuid NOT NULL REFERENCES organization.business_units (id),
    organization_id  uuid NOT NULL REFERENCES organization.organizations (id),
    code             varchar(100) NOT NULL,
    name_en          varchar(255),
    name_vi          varchar(255),
    phone            varchar(30),
    email            varchar(255),
    timezone         varchar(100),
    status           organization.location_status NOT NULL,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    deleted_at       timestamptz,
    CONSTRAINT locations_display_name_chk CHECK (name_en IS NOT NULL OR name_vi IS NOT NULL)
);

CREATE UNIQUE INDEX locations_bu_code_uidx ON organization.locations (business_unit_id, code) WHERE deleted_at IS NULL;
CREATE INDEX locations_organization_id_idx ON organization.locations (organization_id);
CREATE INDEX locations_business_unit_id_idx ON organization.locations (business_unit_id);
CREATE INDEX locations_status_idx ON organization.locations (status);

CREATE TABLE organization.location_addresses (
    id            uuid PRIMARY KEY,
    location_id   uuid NOT NULL UNIQUE REFERENCES organization.locations (id),
    country_id    uuid,
    state         varchar(100),
    city          varchar(100),
    district      varchar(100),
    ward          varchar(100),
    address_line_1 varchar(255),
    address_line_2 varchar(255),
    postal_code   varchar(20),
    latitude      numeric(10, 7),
    longitude     numeric(10, 7),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE organization.location_settings (
    id                     uuid PRIMARY KEY,
    location_id            uuid NOT NULL UNIQUE REFERENCES organization.locations (id),
    booking_settings       jsonb,
    pricing_settings       jsonb,
    calendar_settings      jsonb,
    notification_settings  jsonb,
    updated_at             timestamptz NOT NULL DEFAULT now()
);

-- Backfill one default business unit per existing organization.
INSERT INTO organization.business_units (id, organization_id, code, name_en, name_vi, status, created_at, updated_at)
SELECT gen_random_uuid(), o.id, 'default',
       COALESCE(NULLIF(o.name_en, ''), o.name_vi),
       COALESCE(NULLIF(o.name_vi, ''), o.name_en),
       'active', now(), now()
FROM organization.organizations o
WHERE o.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM organization.business_units bu WHERE bu.organization_id = o.id AND bu.code = 'default'
  );

ALTER TABLE organization.staff_members
    ADD CONSTRAINT staff_members_location_id_fkey
    FOREIGN KEY (location_id) REFERENCES organization.locations (id);


-- >>> 00011_crm_w3_customers.sql
CREATE SCHEMA IF NOT EXISTS crm;

CREATE TYPE crm.customer_status AS ENUM ('lead', 'active', 'inactive', 'blacklisted', 'deleted');
CREATE TYPE crm.customer_type AS ENUM ('individual', 'organization');
CREATE TYPE crm.contact_type AS ENUM ('email', 'phone', 'whatsapp', 'zalo', 'telegram', 'facebook', 'other');

CREATE TABLE crm.customers (
    id                 uuid PRIMARY KEY,
    public_id          varchar(26) NOT NULL UNIQUE,
    tenant_id          uuid NOT NULL REFERENCES organization.tenants (id),
    code               varchar(100) NOT NULL,
    customer_type      crm.customer_type NOT NULL,
    status             crm.customer_status NOT NULL,
    user_id            uuid REFERENCES identity.users (id),
    organization_name  varchar(255),
    owner_staff_id     uuid,
    source             varchar(100),
    acquired_at        timestamptz,
    created_at         timestamptz NOT NULL,
    updated_at         timestamptz NOT NULL,
    deleted_at         timestamptz
);

CREATE UNIQUE INDEX customers_tenant_code_uidx
    ON crm.customers (tenant_id, code) WHERE deleted_at IS NULL;
CREATE INDEX customers_tenant_id_idx ON crm.customers (tenant_id);
CREATE INDEX customers_status_idx ON crm.customers (status);
CREATE INDEX customers_user_id_idx ON crm.customers (user_id);
CREATE INDEX customers_owner_staff_id_idx ON crm.customers (owner_staff_id);

CREATE TABLE crm.customer_profiles (
    id                   uuid PRIMARY KEY,
    customer_id          uuid NOT NULL UNIQUE REFERENCES crm.customers (id),
    first_name           varchar(100),
    last_name            varchar(100),
    full_name            varchar(255),
    gender               varchar(20),
    date_of_birth        date,
    avatar_file_id       uuid,
    occupation           varchar(255),
    company              varchar(255),
    tax_code             varchar(100),
    preferred_locale_id  uuid,
    preferred_timezone   varchar(100),
    metadata             jsonb,
    updated_at           timestamptz NOT NULL
);

CREATE TABLE crm.customer_contacts (
    id            uuid PRIMARY KEY,
    customer_id   uuid NOT NULL REFERENCES crm.customers (id),
    contact_type  crm.contact_type NOT NULL,
    value         varchar(255) NOT NULL,
    label         varchar(100),
    is_verified   boolean NOT NULL DEFAULT false,
    is_primary    boolean NOT NULL DEFAULT false,
    verified_at   timestamptz,
    created_at    timestamptz NOT NULL,
    updated_at    timestamptz NOT NULL
);

CREATE INDEX customer_contacts_customer_id_idx ON crm.customer_contacts (customer_id);
CREATE INDEX customer_contacts_type_value_idx ON crm.customer_contacts (contact_type, lower(value));

-- One primary phone row per customer. Cross-customer tenant uniqueness enforced in application (W3 freeze).
CREATE UNIQUE INDEX customer_contacts_primary_phone_per_customer_uidx
    ON crm.customer_contacts (customer_id)
    WHERE contact_type = 'phone' AND is_primary = true;


-- >>> 00012_catalog_w4_courts.sql
CREATE SCHEMA IF NOT EXISTS catalog;

CREATE TYPE catalog.resource_status AS ENUM ('active', 'inactive', 'maintenance', 'archived');
CREATE TYPE catalog.resource_type AS ENUM ('court', 'room', 'coach', 'equipment', 'facility');
CREATE TYPE catalog.resource_category_status AS ENUM ('active', 'archived');
CREATE TYPE catalog.maintenance_status AS ENUM ('scheduled', 'in_progress', 'completed', 'canceled');

CREATE TABLE catalog.resource_categories (
    id                      uuid PRIMARY KEY,
    tenant_id               uuid NOT NULL REFERENCES organization.tenants (id),
    parent_id               uuid,
    code                    varchar(100) NOT NULL,
    name_en                 varchar(255),
    name_vi                 varchar(255),
    resource_type           catalog.resource_type NOT NULL,
    status                  catalog.resource_category_status NOT NULL,
    slot_duration_minutes   int NOT NULL,
    created_at              timestamptz NOT NULL,
    updated_at              timestamptz NOT NULL,
    deleted_at              timestamptz
);

CREATE UNIQUE INDEX resource_categories_tenant_code_uidx
    ON catalog.resource_categories (tenant_id, code) WHERE deleted_at IS NULL;
CREATE INDEX resource_categories_tenant_id_idx ON catalog.resource_categories (tenant_id);
CREATE INDEX resource_categories_status_idx ON catalog.resource_categories (status);

CREATE TABLE catalog.resources (
    id                  uuid PRIMARY KEY,
    public_id           varchar(26) NOT NULL UNIQUE,
    tenant_id           uuid NOT NULL REFERENCES organization.tenants (id),
    location_id         uuid NOT NULL REFERENCES organization.locations (id),
    court_type_id       uuid REFERENCES catalog.resource_categories (id),
    code                varchar(100) NOT NULL,
    name_en             varchar(255),
    name_vi             varchar(255),
    resource_type       catalog.resource_type NOT NULL,
    parent_resource_id  uuid,
    status              catalog.resource_status NOT NULL,
    is_bookable         boolean NOT NULL DEFAULT true,
    capacity            int,
    sort_order          int DEFAULT 0,
    metadata            jsonb,
    created_at          timestamptz NOT NULL,
    updated_at          timestamptz NOT NULL,
    deleted_at          timestamptz
);

CREATE UNIQUE INDEX courts_location_code_uidx
    ON catalog.resources (location_id, code)
    WHERE deleted_at IS NULL AND resource_type = 'court';
CREATE INDEX resources_tenant_id_idx ON catalog.resources (tenant_id);
CREATE INDEX resources_location_id_idx ON catalog.resources (location_id);
CREATE INDEX resources_court_type_id_idx ON catalog.resources (court_type_id);
CREATE INDEX resources_status_idx ON catalog.resources (status);

CREATE TABLE catalog.resource_maintenances (
    id                   uuid PRIMARY KEY,
    resource_id          uuid NOT NULL REFERENCES catalog.resources (id),
    status               catalog.maintenance_status NOT NULL,
    title                varchar(255),
    description          text,
    started_at           timestamptz,
    completed_at         timestamptz,
    next_maintenance_at  timestamptz,
    created_at           timestamptz NOT NULL,
    updated_at           timestamptz NOT NULL
);

CREATE INDEX resource_maintenances_resource_id_idx ON catalog.resource_maintenances (resource_id);
CREATE INDEX resource_maintenances_status_idx ON catalog.resource_maintenances (status);
CREATE UNIQUE INDEX resource_maintenances_in_progress_uidx
    ON catalog.resource_maintenances (resource_id) WHERE status = 'in_progress';


-- >>> 00013_scheduling_w5.sql
CREATE SCHEMA IF NOT EXISTS scheduling;

CREATE TYPE scheduling.block_type AS ENUM (
    'reservation', 'booking', 'maintenance', 'holiday', 'manual', 'system'
);
CREATE TYPE scheduling.projection_status AS ENUM ('pending', 'generated', 'expired');

CREATE TABLE scheduling.business_hours (
    id          uuid PRIMARY KEY,
    location_id uuid NOT NULL REFERENCES organization.locations (id),
    weekday     smallint NOT NULL CHECK (weekday >= 0 AND weekday <= 6),
    opens_at    time NOT NULL,
    closes_at   time NOT NULL,
    is_closed   boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL
);

CREATE UNIQUE INDEX business_hours_location_weekday_uidx
    ON scheduling.business_hours (location_id, weekday);
CREATE INDEX business_hours_location_id_idx ON scheduling.business_hours (location_id);

CREATE TABLE scheduling.calendar_holidays (
    id          uuid PRIMARY KEY,
    tenant_id   uuid NOT NULL REFERENCES organization.tenants (id),
    location_id uuid REFERENCES organization.locations (id),
    name_en     varchar(255),
    name_vi     varchar(255),
    starts_at   timestamptz NOT NULL,
    ends_at     timestamptz NOT NULL,
    is_closed   boolean NOT NULL DEFAULT true,
    opens_at    time,
    closes_at   time,
    created_at  timestamptz NOT NULL,
    CONSTRAINT calendar_holidays_range_chk CHECK (ends_at > starts_at)
);

CREATE INDEX calendar_holidays_tenant_id_idx ON scheduling.calendar_holidays (tenant_id);
CREATE INDEX calendar_holidays_location_id_idx ON scheduling.calendar_holidays (location_id);
CREATE INDEX calendar_holidays_starts_at_idx ON scheduling.calendar_holidays (starts_at);

CREATE TABLE scheduling.resource_blocks (
    id              uuid PRIMARY KEY,
    resource_id     uuid NOT NULL REFERENCES catalog.resources (id),
    block_type      scheduling.block_type NOT NULL,
    reference_type  varchar(100),
    reference_id    uuid,
    starts_at       timestamptz NOT NULL,
    ends_at         timestamptz NOT NULL,
    reason          text,
    created_at      timestamptz NOT NULL,
    CONSTRAINT resource_blocks_range_chk CHECK (ends_at > starts_at)
);

CREATE INDEX resource_blocks_resource_id_idx ON scheduling.resource_blocks (resource_id);
CREATE INDEX resource_blocks_block_type_idx ON scheduling.resource_blocks (block_type);
CREATE INDEX resource_blocks_starts_at_idx ON scheduling.resource_blocks (starts_at);
CREATE INDEX resource_blocks_ends_at_idx ON scheduling.resource_blocks (ends_at);
CREATE UNIQUE INDEX resource_blocks_maintenance_ref_uidx
    ON scheduling.resource_blocks (resource_id, reference_id)
    WHERE block_type = 'maintenance' AND reference_id IS NOT NULL;

CREATE TABLE scheduling.availability_projections (
    id                 uuid PRIMARY KEY,
    resource_id        uuid NOT NULL REFERENCES catalog.resources (id),
    projection_date    date NOT NULL,
    available_minutes  int NOT NULL,
    occupied_minutes   int NOT NULL,
    status             scheduling.projection_status NOT NULL,
    generated_at       timestamptz NOT NULL
);

CREATE UNIQUE INDEX availability_projections_resource_date_uidx
    ON scheduling.availability_projections (resource_id, projection_date);
CREATE INDEX availability_projections_resource_id_idx ON scheduling.availability_projections (resource_id);

CREATE TABLE scheduling.time_slots (
    id            uuid PRIMARY KEY,
    resource_id   uuid NOT NULL REFERENCES catalog.resources (id),
    starts_at     timestamptz NOT NULL,
    ends_at       timestamptz NOT NULL,
    is_available  boolean NOT NULL,
    source        varchar(100),
    projection_id uuid REFERENCES scheduling.availability_projections (id),
    generated_at  timestamptz NOT NULL
);

CREATE UNIQUE INDEX time_slots_resource_starts_uidx
    ON scheduling.time_slots (resource_id, starts_at);
CREATE INDEX time_slots_resource_id_idx ON scheduling.time_slots (resource_id);
CREATE INDEX time_slots_is_available_idx ON scheduling.time_slots (is_available);


-- >>> 00014_pricing_w6.sql
CREATE SCHEMA IF NOT EXISTS pricing;

CREATE TYPE pricing.price_list_status AS ENUM ('draft', 'active', 'archived');
CREATE TYPE pricing.price_version_status AS ENUM ('draft', 'active', 'retired');
CREATE TYPE pricing.adjustment_type AS ENUM ('surcharge', 'discount');
CREATE TYPE pricing.pricing_rule_type AS ENUM ('fixed', 'percentage', 'formula');

CREATE TABLE pricing.price_lists (
    id          uuid PRIMARY KEY,
    tenant_id   uuid NOT NULL REFERENCES organization.tenants (id),
    code        varchar(100) NOT NULL,
    name_en     varchar(255),
    name_vi     varchar(255),
    currency    varchar(10) NOT NULL DEFAULT 'VND',
    status      pricing.price_list_status NOT NULL DEFAULT 'active',
    created_at  timestamptz NOT NULL,
    updated_at  timestamptz NOT NULL
);

CREATE UNIQUE INDEX price_lists_tenant_code_uidx ON pricing.price_lists (tenant_id, code);
CREATE INDEX price_lists_tenant_id_idx ON pricing.price_lists (tenant_id);
CREATE INDEX price_lists_status_idx ON pricing.price_lists (status);

CREATE TABLE pricing.price_versions (
    id              uuid PRIMARY KEY,
    price_list_id   uuid NOT NULL REFERENCES pricing.price_lists (id),
    version         int NOT NULL,
    status          pricing.price_version_status NOT NULL DEFAULT 'draft',
    effective_from  timestamptz NOT NULL,
    effective_to    timestamptz,
    published_at    timestamptz,
    created_at      timestamptz NOT NULL,
    updated_at      timestamptz NOT NULL
);

CREATE UNIQUE INDEX price_versions_list_version_uidx ON pricing.price_versions (price_list_id, version);
CREATE INDEX price_versions_price_list_id_idx ON pricing.price_versions (price_list_id);
CREATE INDEX price_versions_status_idx ON pricing.price_versions (status);
CREATE UNIQUE INDEX price_versions_one_active_uidx
    ON pricing.price_versions (price_list_id)
    WHERE status = 'active';

CREATE TABLE pricing.category_prices (
    id               uuid PRIMARY KEY,
    price_version_id uuid NOT NULL REFERENCES pricing.price_versions (id) ON DELETE CASCADE,
    category_id      uuid NOT NULL REFERENCES catalog.resource_categories (id),
    amount           numeric(18, 2) NOT NULL CHECK (amount >= 0),
    created_at       timestamptz NOT NULL
);

CREATE UNIQUE INDEX category_prices_version_category_uidx
    ON pricing.category_prices (price_version_id, category_id);
CREATE INDEX category_prices_price_version_id_idx ON pricing.category_prices (price_version_id);
CREATE INDEX category_prices_category_id_idx ON pricing.category_prices (category_id);

CREATE TABLE pricing.time_rules (
    id               uuid PRIMARY KEY,
    price_version_id uuid NOT NULL REFERENCES pricing.price_versions (id) ON DELETE CASCADE,
    weekdays         smallint[] NOT NULL,
    starts_at        time NOT NULL,
    ends_at          time NOT NULL,
    adjustment_type  pricing.adjustment_type NOT NULL,
    value_type       pricing.pricing_rule_type NOT NULL,
    value            numeric(18, 2) NOT NULL,
    priority         int NOT NULL DEFAULT 100,
    created_at       timestamptz NOT NULL,
    CONSTRAINT time_rules_window_chk CHECK (ends_at > starts_at),
    CONSTRAINT time_rules_value_type_chk CHECK (value_type IN ('fixed', 'percentage'))
);

CREATE INDEX time_rules_price_version_id_idx ON pricing.time_rules (price_version_id);
CREATE INDEX time_rules_priority_idx ON pricing.time_rules (priority);


-- >>> 00015_reservation_booking_w7.sql
CREATE SCHEMA IF NOT EXISTS reservation;
CREATE SCHEMA IF NOT EXISTS booking;
CREATE SCHEMA IF NOT EXISTS billing;

CREATE TYPE reservation.reservation_status AS ENUM (
    'pending', 'converted', 'canceled', 'expired'
);
CREATE TYPE reservation.reservation_source AS ENUM (
    'web', 'mobile', 'admin', 'api', 'staff'
);

CREATE TYPE booking.booking_status AS ENUM (
    'pending', 'confirmed', 'checked_in', 'in_progress', 'completed', 'canceled'
);

CREATE TYPE billing.invoice_status AS ENUM (
    'draft', 'issued', 'partially_paid', 'paid', 'void', 'canceled'
);

CREATE TABLE reservation.reservations (
    id               uuid PRIMARY KEY,
    public_id        varchar(26) NOT NULL UNIQUE,
    tenant_id        uuid NOT NULL REFERENCES organization.tenants (id),
    reservation_no   varchar(50) NOT NULL UNIQUE,
    customer_id      uuid NOT NULL REFERENCES crm.customers (id),
    location_id      uuid NOT NULL REFERENCES organization.locations (id),
    resource_id      uuid NOT NULL REFERENCES catalog.resources (id),
    source           reservation.reservation_source NOT NULL,
    status           reservation.reservation_status NOT NULL DEFAULT 'pending',
    currency         varchar(10) NOT NULL DEFAULT 'VND',
    subtotal         numeric(18, 2) NOT NULL DEFAULT 0,
    discount_amount  numeric(18, 2) NOT NULL DEFAULT 0,
    tax_amount       numeric(18, 2) NOT NULL DEFAULT 0,
    total_amount     numeric(18, 2) NOT NULL DEFAULT 0,
    price_version_id uuid REFERENCES pricing.price_versions (id),
    starts_at        timestamptz NOT NULL,
    ends_at          timestamptz NOT NULL,
    expires_at       timestamptz NOT NULL,
    canceled_at      timestamptz,
    converted_at     timestamptz,
    created_by       uuid,
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL,
    CONSTRAINT reservations_range_chk CHECK (ends_at > starts_at)
);

CREATE INDEX reservations_tenant_id_idx ON reservation.reservations (tenant_id);
CREATE INDEX reservations_customer_id_idx ON reservation.reservations (customer_id);
CREATE INDEX reservations_status_idx ON reservation.reservations (status);
CREATE INDEX reservations_expires_at_idx ON reservation.reservations (expires_at);
CREATE INDEX reservations_resource_id_idx ON reservation.reservations (resource_id);

CREATE TABLE reservation.reservation_resources (
    id              uuid PRIMARY KEY,
    reservation_id  uuid NOT NULL REFERENCES reservation.reservations (id) ON DELETE CASCADE,
    resource_id     uuid NOT NULL REFERENCES catalog.resources (id),
    starts_at       timestamptz NOT NULL,
    ends_at         timestamptz NOT NULL,
    created_at      timestamptz NOT NULL,
    CONSTRAINT reservation_resources_range_chk CHECK (ends_at > starts_at)
);

CREATE INDEX reservation_resources_reservation_id_idx ON reservation.reservation_resources (reservation_id);
CREATE INDEX reservation_resources_resource_id_idx ON reservation.reservation_resources (resource_id);

CREATE TABLE booking.bookings (
    id               uuid PRIMARY KEY,
    public_id        varchar(26) NOT NULL UNIQUE,
    tenant_id        uuid NOT NULL REFERENCES organization.tenants (id),
    booking_no       varchar(50) NOT NULL UNIQUE,
    reservation_id   uuid REFERENCES reservation.reservations (id),
    customer_id      uuid NOT NULL REFERENCES crm.customers (id),
    location_id      uuid NOT NULL REFERENCES organization.locations (id),
    resource_id      uuid NOT NULL REFERENCES catalog.resources (id),
    status           booking.booking_status NOT NULL DEFAULT 'pending',
    currency         varchar(10) NOT NULL DEFAULT 'VND',
    subtotal         numeric(18, 2) NOT NULL DEFAULT 0,
    discount_amount  numeric(18, 2) NOT NULL DEFAULT 0,
    tax_amount       numeric(18, 2) NOT NULL DEFAULT 0,
    total_amount     numeric(18, 2) NOT NULL DEFAULT 0,
    price_version_id uuid REFERENCES pricing.price_versions (id),
    starts_at        timestamptz NOT NULL,
    ends_at          timestamptz NOT NULL,
    expires_at       timestamptz,
    confirmed_at     timestamptz,
    canceled_at      timestamptz,
    completed_at     timestamptz,
    checked_in_at    timestamptz,
    created_by       uuid,
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL,
    CONSTRAINT bookings_range_chk CHECK (ends_at > starts_at)
);

CREATE INDEX bookings_tenant_id_idx ON booking.bookings (tenant_id);
CREATE INDEX bookings_customer_id_idx ON booking.bookings (customer_id);
CREATE INDEX bookings_location_id_idx ON booking.bookings (location_id);
CREATE INDEX bookings_status_idx ON booking.bookings (status);
CREATE INDEX bookings_resource_id_idx ON booking.bookings (resource_id);
CREATE INDEX bookings_expires_at_idx ON booking.bookings (expires_at);
CREATE INDEX bookings_starts_at_idx ON booking.bookings (starts_at);

CREATE TABLE booking.booking_resources (
    id          uuid PRIMARY KEY,
    booking_id  uuid NOT NULL REFERENCES booking.bookings (id) ON DELETE CASCADE,
    resource_id uuid NOT NULL REFERENCES catalog.resources (id),
    starts_at   timestamptz NOT NULL,
    ends_at     timestamptz NOT NULL,
    created_at  timestamptz NOT NULL,
    CONSTRAINT booking_resources_range_chk CHECK (ends_at > starts_at)
);

CREATE INDEX booking_resources_booking_id_idx ON booking.booking_resources (booking_id);
CREATE INDEX booking_resources_resource_id_idx ON booking.booking_resources (resource_id);

CREATE TABLE booking.check_ins (
    id            uuid PRIMARY KEY,
    booking_id    uuid NOT NULL REFERENCES booking.bookings (id) ON DELETE CASCADE,
    checked_in_at timestamptz NOT NULL,
    verified_by   uuid,
    created_at    timestamptz NOT NULL
);

CREATE UNIQUE INDEX check_ins_booking_id_uidx ON booking.check_ins (booking_id);

CREATE TABLE billing.invoices (
    id               uuid PRIMARY KEY,
    public_id        varchar(26) NOT NULL UNIQUE,
    tenant_id        uuid NOT NULL REFERENCES organization.tenants (id),
    invoice_no       varchar(50) NOT NULL UNIQUE,
    booking_id       uuid NOT NULL REFERENCES booking.bookings (id),
    customer_id      uuid NOT NULL REFERENCES crm.customers (id),
    currency         varchar(10) NOT NULL DEFAULT 'VND',
    status           billing.invoice_status NOT NULL DEFAULT 'issued',
    subtotal         numeric(18, 2) NOT NULL DEFAULT 0,
    discount_amount  numeric(18, 2) NOT NULL DEFAULT 0,
    tax_amount       numeric(18, 2) NOT NULL DEFAULT 0,
    total_amount     numeric(18, 2) NOT NULL DEFAULT 0,
    issued_at        timestamptz NOT NULL,
    due_at           timestamptz,
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz NOT NULL
);

CREATE INDEX invoices_tenant_id_idx ON billing.invoices (tenant_id);
CREATE INDEX invoices_booking_id_idx ON billing.invoices (booking_id);
CREATE INDEX invoices_customer_id_idx ON billing.invoices (customer_id);
CREATE INDEX invoices_status_idx ON billing.invoices (status);

CREATE UNIQUE INDEX resource_blocks_reservation_ref_uidx
    ON scheduling.resource_blocks (resource_id, reference_id)
    WHERE block_type = 'reservation' AND reference_id IS NOT NULL;

CREATE UNIQUE INDEX resource_blocks_booking_ref_uidx
    ON scheduling.resource_blocks (resource_id, reference_id)
    WHERE block_type = 'booking' AND reference_id IS NOT NULL;


-- >>> 00016_payment_w8.sql
ALTER TABLE billing.invoices
    ADD COLUMN IF NOT EXISTS paid_at timestamptz,
    ADD COLUMN IF NOT EXISTS refunded_amount numeric(18, 2) NOT NULL DEFAULT 0;

CREATE SCHEMA IF NOT EXISTS payment;

CREATE TYPE payment.payment_intent_status AS ENUM (
    'pending', 'succeeded', 'failed', 'expired'
);
CREATE TYPE payment.payment_method_type AS ENUM (
    'cash', 'mock'
);
CREATE TYPE payment.refund_status AS ENUM (
    'pending', 'completed', 'failed', 'canceled'
);

CREATE TABLE payment.payment_intents (
    id            uuid PRIMARY KEY,
    tenant_id     uuid NOT NULL REFERENCES organization.tenants (id),
    invoice_id    uuid NOT NULL REFERENCES billing.invoices (id),
    customer_id   uuid NOT NULL REFERENCES crm.customers (id),
    amount        numeric(18, 2) NOT NULL CHECK (amount > 0),
    currency      varchar(10) NOT NULL DEFAULT 'VND',
    status        payment.payment_intent_status NOT NULL DEFAULT 'pending',
    method_type   payment.payment_method_type NOT NULL,
    expires_at    timestamptz,
    succeeded_at  timestamptz,
    created_by    uuid,
    created_at    timestamptz NOT NULL,
    updated_at    timestamptz NOT NULL
);

CREATE INDEX payment_intents_tenant_id_idx ON payment.payment_intents (tenant_id);
CREATE INDEX payment_intents_invoice_id_idx ON payment.payment_intents (invoice_id);
CREATE INDEX payment_intents_customer_id_idx ON payment.payment_intents (customer_id);
CREATE INDEX payment_intents_status_idx ON payment.payment_intents (status);
CREATE INDEX payment_intents_expires_at_idx ON payment.payment_intents (expires_at);
CREATE UNIQUE INDEX payment_intents_open_invoice_uidx
    ON payment.payment_intents (invoice_id)
    WHERE status IN ('pending', 'succeeded');

CREATE TABLE payment.refunds (
    id                 uuid PRIMARY KEY,
    tenant_id          uuid NOT NULL REFERENCES organization.tenants (id),
    payment_intent_id  uuid NOT NULL REFERENCES payment.payment_intents (id),
    invoice_id         uuid NOT NULL REFERENCES billing.invoices (id),
    amount             numeric(18, 2) NOT NULL CHECK (amount > 0),
    currency           varchar(10) NOT NULL DEFAULT 'VND',
    status             payment.refund_status NOT NULL DEFAULT 'completed',
    created_by         uuid,
    created_at         timestamptz NOT NULL,
    updated_at         timestamptz NOT NULL
);

CREATE INDEX refunds_tenant_id_idx ON payment.refunds (tenant_id);
CREATE INDEX refunds_payment_intent_id_idx ON payment.refunds (payment_intent_id);
CREATE INDEX refunds_invoice_id_idx ON payment.refunds (invoice_id);
CREATE UNIQUE INDEX refunds_one_completed_intent_uidx
    ON payment.refunds (payment_intent_id)
    WHERE status = 'completed';


-- >>> 00017_locales_emoji.sql
ALTER TABLE reference.locales
    ADD COLUMN emoji varchar(16) NOT NULL DEFAULT '';

UPDATE reference.locales
SET emoji = '🇻🇳',
    name = 'Vietnamese',
    native_name = 'Tiếng Việt',
    updated_at = now()
WHERE code = 'vi';

UPDATE reference.locales
SET emoji = '🇬🇧',
    name = 'English',
    native_name = 'English',
    updated_at = now()
WHERE code = 'en';

ALTER TABLE reference.locales
    ALTER COLUMN emoji DROP DEFAULT;


