#!/usr/bin/env bash
# Extract -- +goose Up blocks from migrations into a single schema file for sqlc.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MIGRATIONS="${ROOT}/backend/migrations"
OUT="${ROOT}/backend/db/schema.sql"

mkdir -p "$(dirname "$OUT")"
{
  echo "-- Generated by scripts/sqlc-schema.sh — do not edit by hand."
  echo "-- Source: backend/migrations (-- +goose Up only)."
  echo
  for f in $(ls "${MIGRATIONS}"/*.sql | sort); do
    echo "-- >>> $(basename "$f")"
    awk '
      /^-- \+goose Down/ { in_up=0; next }
      /^-- \+goose Up/ { in_up=1; next }
      in_up { print }
    ' "$f"
    echo
  done
} > "$OUT"

echo "wrote $OUT"
